title: Thomas von Fürstenfeld
lang: hu
locale: hu_HU
author: 'Iván Gábor'
author_slug: '/gabor.ivan/'
author_avatar: '/assets/img/gabor.ivan.jpg'
author_cover: '/assets/img/gabor.ivan-cover.jpg'
author_introduction: 'Férje egy csodálatos asszonynak, apja egy nagyszerű fiúnak, gazdája egy gyönyörű macskának. Foglalkozását tekintve web-fejlesztő egy németországi, de nemzetközi vizekre merészkedő fiatal E-kereskedelemmel foglalkozó cégnél.'
description: 'Személyes jellegű blogbejegyzések gyűjteménye a Németországba való kiköltözésről és a beilleszkedésről.'
subject: 'Személyes blog, amit azért hoztam létre, hogy lehetőség szerint hasznos tanácsokkal és információkkal lássam el a kivándorolni vágyó honfitársaimat.'
copyright: 'Copyright © 2002-2019, Gixx-web (https://www.gixx-web.com). Minden jog fenntartva.'
keywords: 'Thomas, Thomas von Fürstenfeld, Németország, Bajorország, München, diszidálás, kiköltözés, emigrálás, beilleszkedés'

homepage: 'https://thomas.von.fuerstenfeld.blog'

default_categories: ['Home']
default_tags: ['']

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
      page_categories: ['Home']
      page_tags: ['']
      page_type: 'post_list'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      page_type: 'post_view'

destination: docs

facebook_appid: 2178081495757871
facebook_username: ivan.gabor.80
twitter_username: gaborivan1980
github_username: Gixx
linkedin_username: gaborivan

future: true

exclude:
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE

env: production

excerpt_separator: <!--more-->

reversed_categories:
  - hasznos

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /:categories/:title.html

autopages:
  enabled: true
  tags:
    layouts:
      - taglist.html
    title: ''
    permalink: /cimkek/:tag/
    enabled: true
  categories:
    layouts:
      - categorylist.html
    title: ''
    permalink: /:cat/
    enabled: true
  collections:
    enabled: false

jekyll-archives:
  enabled:
    - month
  layouts:
    month: 'datelist'
  permalinks:
    month: '/archivum/:year-:month/'

pagination:
  enabled: true
  per_page: 6
  offset: 0
  permalink: '/oldal/:num.html'
  title: ':title - :num. oldal'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-archives
  - jekyll-include-cache
  - rouge
  - jekyll-last-modified-at
  - jekyll-plantuml
  - jekyll-tidy
  - classifier-reborn
  - jekyll-tagging-related_posts
  - jekyll-paginate-v2

jekyll_tidy:
  exclude: ['robots.txt']
  compress_html: false

sass:
  sass_dir: _sass
  sourcemap: true
  style: compressed
